export interface NewsletterSource {
  name: string
  url: string
  rssUrl?: string
  category: string
  geo: string
  frequency: string
  apiType: "rss" | "api" | "scrape"
}

export const newsletterSources: NewsletterSource[] = [
  // Product Management - Africa/Nigeria
  {
    name: "TechCabal",
    url: "https://techcabal.com",
    rssUrl: "https://techcabal.com/feed/",
    category: "product",
    geo: "africa",
    frequency: "daily",
    apiType: "rss",
  },
  {
    name: "Techpoint Africa",
    url: "https://techpoint.africa",
    rssUrl: "https://techpoint.africa/feed/",
    category: "product",
    geo: "africa",
    frequency: "daily",
    apiType: "rss",
  },
  {
    name: "Big Cabal Media",
    url: "https://www.bigcabal.com",
    rssUrl: "https://www.bigcabal.com/feed/",
    category: "product",
    geo: "nigeria",
    frequency: "weekly",
    apiType: "rss",
  },

  // Product Management - Global
  {
    name: "Lenny's Newsletter",
    url: "https://www.lennysnewsletter.com",
    rssUrl: "https://www.lennysnewsletter.com/feed",
    category: "product",
    geo: "global",
    frequency: "weekly",
    apiType: "rss",
  },
  {
    name: "Mind the Product",
    url: "https://www.mindtheproduct.com",
    rssUrl: "https://www.mindtheproduct.com/feed/",
    category: "product",
    geo: "global",
    frequency: "weekly",
    apiType: "rss",
  },
  {
    name: "Product School",
    url: "https://productschool.com/blog",
    rssUrl: "https://productschool.com/blog/feed/",
    category: "product",
    geo: "global",
    frequency: "daily",
    apiType: "rss",
  },
  {
    name: "SVPG Blog",
    url: "https://www.svpg.com",
    rssUrl: "https://www.svpg.com/feed/",
    category: "product",
    geo: "global",
    frequency: "weekly",
    apiType: "rss",
  },

  // Web3/Crypto - Africa/Nigeria
  {
    name: "Web3Bridge",
    url: "https://web3bridge.com",
    rssUrl: "https://web3bridge.com/feed/",
    category: "stablecoins",
    geo: "africa",
    frequency: "weekly",
    apiType: "rss",
  },
  {
    name: "Yellow Card Blog",
    url: "https://yellowcard.io",
    rssUrl: "https://yellowcard.io/blog/feed/",
    category: "stablecoins",
    geo: "africa",
    frequency: "weekly",
    apiType: "rss",
  },
  {
    name: "Bundle Africa",
    url: "https://bundle.africa",
    rssUrl: "https://bundle.africa/blog/feed/",
    category: "stablecoins",
    geo: "africa",
    frequency: "weekly",
    apiType: "rss",
  },

  // Web3/Crypto - Global
  {
    name: "The Defiant",
    url: "https://thedefiant.io",
    rssUrl: "https://thedefiant.io/feed/",
    category: "stablecoins",
    geo: "global",
    frequency: "daily",
    apiType: "rss",
  },
  {
    name: "Bankless",
    url: "https://banklesshq.com",
    rssUrl: "https://banklesshq.com/feed/",
    category: "stablecoins",
    geo: "global",
    frequency: "weekly",
    apiType: "rss",
  },
  {
    name: "CoinDesk",
    url: "https://www.coindesk.com",
    rssUrl: "https://www.coindesk.com/arc/outboundfeeds/rss/",
    category: "stablecoins",
    geo: "global",
    frequency: "daily",
    apiType: "rss",
  },
  {
    name: "Messari",
    url: "https://messari.io",
    rssUrl: "https://messari.io/rss",
    category: "stablecoins",
    geo: "global",
    frequency: "daily",
    apiType: "rss",
  },

  // Stablecoins - Global
  {
    name: "Circle Blog",
    url: "https://www.circle.com/blog",
    rssUrl: "https://www.circle.com/blog/feed",
    category: "stablecoins",
    geo: "global",
    frequency: "weekly",
    apiType: "rss",
  },
  {
    name: "MakerDAO Blog",
    url: "https://blog.makerdao.com",
    rssUrl: "https://blog.makerdao.com/feed/",
    category: "stablecoins",
    geo: "global",
    frequency: "weekly",
    apiType: "rss",
  },
  {
    name: "Tether Blog",
    url: "https://tether.to",
    rssUrl: "https://tether.to/en/feed/",
    category: "stablecoins",
    geo: "global",
    frequency: "weekly",
    apiType: "rss",
  },

  // Tech for Non-Techs - Africa/Nigeria
  {
    name: "ForLoop Africa",
    url: "https://forloop.africa",
    rssUrl: "https://forloop.africa/feed/",
    category: "tech-for-non-techs",
    geo: "africa",
    frequency: "weekly",
    apiType: "rss",
  },
  {
    name: "She Code Africa",
    url: "https://shecodeafrica.org",
    rssUrl: "https://shecodeafrica.org/feed/",
    category: "tech-for-non-techs",
    geo: "africa",
    frequency: "weekly",
    apiType: "rss",
  },
  {
    name: "Zikoko Tech",
    url: "https://www.zikoko.com",
    rssUrl: "https://www.zikoko.com/feed/",
    category: "tech-for-non-techs",
    geo: "nigeria",
    frequency: "daily",
    apiType: "rss",
  },

  // Tech for Non-Techs - Global
  {
    name: "The Pragmatic Engineer",
    url: "https://blog.pragmaticengineer.com",
    rssUrl: "https://blog.pragmaticengineer.com/feed/",
    category: "tech-for-non-techs",
    geo: "global",
    frequency: "weekly",
    apiType: "rss",
  },
  {
    name: "Stack Overflow Blog",
    url: "https://stackoverflow.blog",
    rssUrl: "https://stackoverflow.blog/feed/",
    category: "tech-for-non-techs",
    geo: "global",
    frequency: "daily",
    apiType: "rss",
  },
  {
    name: "ByteByteGo",
    url: "https://blog.bytebytego.com",
    rssUrl: "https://blog.bytebytego.com/feed",
    category: "tech-for-non-techs",
    geo: "global",
    frequency: "weekly",
    apiType: "rss",
  },
  {
    name: "Frontend Horse",
    url: "https://frontend.horse",
    rssUrl: "https://frontend.horse/feed.xml",
    category: "tech-for-non-techs",
    geo: "global",
    frequency: "weekly",
    apiType: "rss",
  },

  // Business - Africa/Nigeria
  {
    name: "Nairametrics",
    url: "https://nairametrics.com",
    rssUrl: "https://nairametrics.com/feed/",
    category: "business",
    geo: "nigeria",
    frequency: "daily",
    apiType: "rss",
  },
  {
    name: "BusinessDay Nigeria",
    url: "https://businessday.ng",
    rssUrl: "https://businessday.ng/feed/",
    category: "business",
    geo: "nigeria",
    frequency: "daily",
    apiType: "rss",
  },

  // Business - Global
  {
    name: "Harvard Business Review",
    url: "https://hbr.org",
    rssUrl: "https://feeds.hbr.org/harvardbusiness",
    category: "business",
    geo: "global",
    frequency: "daily",
    apiType: "rss",
  },
  {
    name: "Fast Company",
    url: "https://www.fastcompany.com",
    rssUrl: "https://www.fastcompany.com/rss",
    category: "business",
    geo: "global",
    frequency: "daily",
    apiType: "rss",
  },
  {
    name: "TechCrunch",
    url: "https://techcrunch.com",
    rssUrl: "https://techcrunch.com/feed/",
    category: "business",
    geo: "global",
    frequency: "daily",
    apiType: "rss",
  },
  {
    name: "Entrepreneur",
    url: "https://www.entrepreneur.com",
    rssUrl: "https://www.entrepreneur.com/latest.rss",
    category: "business",
    geo: "global",
    frequency: "daily",
    apiType: "rss",
  },

  // Additional reliable sources for better coverage
  {
    name: "Wired",
    url: "https://www.wired.com",
    rssUrl: "https://www.wired.com/feed/rss",
    category: "tech-for-non-techs",
    geo: "global",
    frequency: "daily",
    apiType: "rss",
  },
  {
    name: "Ars Technica",
    url: "https://arstechnica.com",
    rssUrl: "https://feeds.arstechnica.com/arstechnica/index",
    category: "tech-for-non-techs",
    geo: "global",
    frequency: "daily",
    apiType: "rss",
  },
  {
    name: "The Verge",
    url: "https://www.theverge.com",
    rssUrl: "https://www.theverge.com/rss/index.xml",
    category: "tech-for-non-techs",
    geo: "global",
    frequency: "daily",
    apiType: "rss",
  },
]
